### PR TITLE
upgrade web image to xenial

### PR DESCRIPTION
**Pull request by CircleCode**
Here is an attemps to use xenial version (following #24).
Here are the changes from the current image:

- add environment variables:
  - `LEMUR_VERSION` (defaults to `master`): branch or tag to fetch and install
  - `LEMUR_TARGET` (defaults to `develop`): makefile target to build
- no more using external repositories for
  - nodejs
  - python 3
- use `/usr/local/src/lemur` as default workdir

But it seems once successfully builded, the application does not run corectly, even when master is builded.

So I suppose there must be a review in case this is linked to this dockerfile.
(especially ping @kevgliss  since even when building master, it seems to still be affected by netflix/lemur#996) 

I should also update Readme to explain variables.

### CODE REVIEW

**Comment by kevgliss** [comment]
When is the last time you've run? netflix/lemur#996 should now be fixed in master. Are there additional errors?

**Comment by CircleCode** [comment]
I've checked it against current master (commit ad88637f22c2e8418db3f96ba473c5f11d421e22)
Running with latest firefox nightly, i get the following errors in the js console:
```
ReferenceError: require is not defined[En savoir plus] vendor.js:80273:1
```
```
Error: [$injector:modulerr] Failed to instantiate module lemur due to:
[$injector:modulerr] Failed to instantiate module chart.js due to:
[$injector:nomod] Module 'chart.js' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.9/$injector/nomod?p0=chart.js
minErr/<@https://localhost/scripts/vendor.js:17042:12
module/<@https://localhost/scripts/vendor.js:18980:17
ensure@https://localhost/scripts/vendor.js:18904:38
module@https://localhost/scripts/vendor.js:18978:14
loadModules/<@https://localhost/scripts/vendor.js:21421:22
forEach@https://localhost/scripts/vendor.js:17315:11
loadModules@https://localhost/scripts/vendor.js:21405:5
loadModules/<@https://localhost/scripts/vendor.js:21422:40
forEach@https://localhost/scripts/vendor.js:17315:11
loadModules@https://localhost/scripts/vendor.js:21405:5
createInjector@https://localhost/scripts/vendor.j… vendor.js:29696:18
```

additionnaly, in the header, `{{ currentUser.username }} {{ currentUser.username }}` is not replaced.

**Comment by kevgliss** [comment]
I'm not sure what to make of this. I've pulled your PR and run `docker-compose up` and was able to login just fine. Are you sure you aren't cached somewhere? I would try `docker-compose build lemur-web`. Regardless this looks excellent and am happy to merge.

**Comment by kevgliss** [comment]
Closes #22 and #24

**Comment by CircleCode** [comment]
it seems i effectively had some cache somewhere, but I really does not know where…
dropping all containers and images, and restarting from scratch solved my issues.

**Pull request merged**
